frontend:
  replicaCount: 1
  image:
    repository: quay.io/rh-ee-dsivan/developer-workshop/exercise-5/frontend
    tag: v1
  service:
    port: 8080
  route:
    enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  backendUrl: "http://backend:8080"
backend:
  replicaCount: 1
  image:
    repository: quay.io/rh-ee-dsivan/developer-workshop/exercise-5/backend
    tag: v1
  service:
    port: 8080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    dbHost: db
    dbPort: 5432
    dbUser: workshopuser
    dbPassword: workshop123
    dbName: notesdb
db:
  replicaCount: 1
  image:
    repository: registry.redhat.io/rhel9/postgresql-16
    tag: latest
  service:
    port: 5432
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  secret:
    name: db
    type: Opaque
    stringData:
      POSTGRESQL_USER: workshopuser
      POSTGRESQL_PASSWORD: workshop123
      POSTGRESQL_DATABASE: notesdb
  mount:
    name: db-data
    mountPath: /var/lib/pgsql/data
    storage: 1Gi
    accessMode: ReadWriteOnce