apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secret.name }}
  labels:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
type: {{ .Values.db.secret.type }}
stringData:
  {{- toYaml .Values.db.secret.stringData | nindent 2 }}
