apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app: db
